// web/app/core/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'gcd-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent {
  openGithub(): void {
    window.open('https://github.com/larscom/gitlab-ci-dashboard', '_blank');
  }
}

<mat-toolbar class="flex justify-between"
  color="primary">
  <div class="flex items-center">
    <button class="flex" mat-icon-button
      aria-label="App icon">
      <mat-icon>apps</mat-icon>
    </button>
    <span>Gitlab CI Dashboard</span>
  </div>
  <img class="cursor-pointer"
    matTooltip="Open Github (source code)"
    matTooltipShowDelay="500"
    matTooltipPosition="left"
    (click)="openGithub()"
    src="./assets/image/github.svg" />
</mat-toolbar>

// src/components/Header.tsx
import { DashboardOutlined, GithubOutlined } from '@ant-design/icons'
import { ActionIcon, Group, Header as H, Text, Tooltip } from '@mantine/core'
import Version from './Version'

export default function Header() {
  const handleClick = () =>
    window.open('https://github.com/larscom/gitlab-ci-dashboard', '_blank')

  return (
    <H height={60} className="flex items-center justify-between bg-blue-600" p="md">
      <Group spacing="xs" align="baseline">
        <DashboardOutlined className="text-white text-xl" />
        <Text className="text-white" size="md">
          Gitlab CI Dashboard
        </Text>
      </Group>
      <Group className="items-baseline" spacing="xs">
        <Version />
        <ActionIcon onClick={handleClick} variant="transparent">
          <Tooltip openDelay={250} label="Source code">
            <GithubOutlined className="text-white text-xl" />
          </Tooltip>
        </ActionIcon>
      </Group>
    </H>
  )
}
