// src/app/header/header.component.ts
import { CommonModule } from '@angular/common'
import { NzToolTipModule } from 'ng-zorro-antd/tooltip'

import { ConfigService } from '$service/config.service'
import { Component, inject } from '@angular/core'
import { NzButtonModule } from 'ng-zorro-antd/button'
import { NzIconModule } from 'ng-zorro-antd/icon'

@Component({
  selector: 'gcd-header',
  imports: [CommonModule, NzIconModule, NzButtonModule, NzToolTipModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  private config = inject(ConfigService)
  readonly version = this.config.version

  onClick(): void {
    window.open('https://github.com/larscom/gitlab-ci-dashboard', '_blank')
  }
}

<header class="header">
  <div><span style="font-size: 20px; color: white" nz-icon nzType="dashboard"></span> Gitlab CI Dashboard</div>
  <div style="display: flex; gap: 0.5rem; align-items: center">
    <div>
      <span style="font-size: var(--font-size-small)">{{ version$ | async }}</span>
    </div>
    <button style="padding: 0" nzType="text" nz-button nz-tooltip nzTooltipTitle="Source code" (click)="onClick()">
      <span style="font-size: 20px; color: white" nz-icon nzType="github"></span>
    </button>
  </div>
</header>

// src/components/Header.tsx
import { DashboardOutlined, GithubOutlined } from '@ant-design/icons'
import { ActionIcon, Group, Header as H, Text, Tooltip } from '@mantine/core'
import Version from './Version'

export default function Header() {
  const handleClick = () =>
    window.open('https://github.com/larscom/gitlab-ci-dashboard', '_blank')

  return (
    <H height={60} className="flex items-center justify-between bg-blue-600" p="md">
      <Group spacing="xs" align="baseline">
        <DashboardOutlined className="text-white text-xl" />
        <Text className="text-white" size="md">
          Gitlab CI Dashboard
        </Text>
      </Group>
      <Group className="items-baseline" spacing="xs">
        <Version />
        <ActionIcon onClick={handleClick} variant="transparent">
          <Tooltip openDelay={250} label="Source code">
            <GithubOutlined className="text-white text-xl" />
          </Tooltip>
        </ActionIcon>
      </Group>
    </H>
  )
}
